#!/usr/bin/env bash
# A Bash script that runs the whoami command the the first argument passed
# to it. Here am assumming the first command passed to the script is  user
# registerred on the system.
sudo -u "$1" whoami
